"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("cities", [
      { name: "-" },
      { name: "BRUDZOWICE" },
      { name: "BIALYSTOK" },
      { name: "KOSZALIN" },
      { name: "PINCZYN" },
      { name: "WARSZAWA" },
      { name: "CHOROSZCZ" },
      { name: "UJAZD" },
      { name: "LABISZYN" },
      { name: "SZCZECIN" },
      { name: "KOBYLKA K.WARSZAWY" },
      { name: "GORNO K/KIELC" },
      { name: "ELK" },
      { name: "PABIANICE" },
      { name: "NISKO" },
      { name: "RAKONIEWICE/WOLSZTYN" },
      { name: "OBORNIKI" },
      { name: "RADOMYSL" },
      { name: "MRAGOWO" },
      { name: "W„SEWO" },
      { name: "KRASOCIN" },
      { name: "GDANSK" },
      { name: "TORUN" },
      { name: "KRAKOW" },
      { name: "ZBLEWO" },
      { name: "GLOGOW MLP" },
      { name: "JAWORZYNA SLASKA" },
      { name: "DZIEŚMOROWICE" },
      { name: "STRZELNO" },
      { name: "MICHALOWICE-REGULY" },
      { name: "RADOMYSL N/SANEM" },
      { name: "CZELADŹ" },
      { name: "SICIENKO" },
      { name: "WLOCLAWEK" },
      { name: "TRZEMESZNO" },
      { name: "PIASECZNO" },
      { name: "PULTUSK" },
      { name: "PSZCZOLKI" },
      { name: "BIESIEKIERZ" },
      { name: "RZESZOW" },
      { name: "OPOCZNO" },
      { name: "TARNOWSKIEGORY" },
      { name: "LABORK" },
      { name: "ZABKOWICE SLASKIE" },
      { name: "RACIECHOWICE" },
      { name: "TYCHY" },
      { name: "RYBNIK" },
      { name: "WOLOMIN" },
      { name: "PLOÁSK" },
      { name: "RYTRO 502" },
      { name: "SREM" },
      { name: "KOBYLKA" },
      { name: "MORAWICA" },
      { name: "BIELSKO-BIALA" },
      { name: "RACIBOROWICE GORNE" },
      { name: "CZESTOCHOWA" },
      { name: "LUBLIN" },
      { name: "GORZOW WLKP" },
      { name: "CIESZYN" },
      { name: "űUKOWO" },
      { name: "KROTOSZYN" },
      { name: "WALCZ" },
      { name: "IZABELIN" },
      { name: "USTKA" },
      { name: "ZAMOSŚ" },
      { name: "RADZIEJOW" },
      { name: "OBORNIKI SLASKIE" },
      { name: "BIESLKO-BIALA" },
      { name: "D„BROWA" },
      { name: "OSIECZNA" },
      { name: "OPATOWEK" },
      { name: "BIELAWA" },
      { name: "STARGARD SZCZECINSKI" },
      { name: "LAGOWO" },
      { name: "SOSNOWIEC" },
      { name: "MIÁSK MAZOWIECKI" },
      { name: "KIELCE" },
      { name: "KONIN" },
      { name: "OSWIACIM" },
      { name: "LESZNOWOLA" },
      { name: "SAPOLNO KRAJEÁSKIE" },
      { name: "ZAWIERCIE" },
      { name: "MALBORK" },
      { name: "PLESZEW" },
      { name: "W„GROWIEC" },
      { name: "ZIELONKA" },
      { name: "CHRZANOW" },
      { name: "LUBAÁ" },
      { name: "BIELSKO BIALA" },
      { name: "GRAJEWO" },
      { name: "KALETY" },
      { name: "BRZESŚ KUJAWSKI" },
      { name: "SUCHY LAS" },
      { name: "BUJAKOW" },
      { name: "LISZKI" },
      { name: "HRUBIESZOW" },
      { name: "GROJEC" },
      { name: "CHORZOW" },
      { name: "BYTOM" },
      { name: "OPOLE" },
      { name: "RUDAWA K/ZABIERZOWA" },
      { name: "NYSA" },
      { name: "GROBLICE" },
      { name: "DABICA" },
      { name: "MIKOLOW" },
      { name: "GABICE" },
      { name: "TARNOW" },
      { name: "SWIDNICA" },
      { name: "SZCZYRK" },
      { name: "RADOM" },
      { name: "GLINCZ K/űUKOWA" },
      { name: "SOPOT" },
      { name: "BYDGOSZCZ" },
      { name: "POTULICE" },
      { name: "STARE BABICE" },
      { name: "PRZEWORSK" },
      { name: "LABOWA" },
      { name: "MIERZYN/DOBRA SZCZECINSKA" },
      { name: "ZAMBROW" },
      { name: "LODZ" },
      { name: "DOBRA SZCZECINSKA" },
      { name: "GNIEWKOWO" },
      { name: "WROCLAW" },
      { name: "PSZCZYNA" },
      { name: "SIANOW" },
      { name: "OSNO LUBUSKIE" },
      { name: "JAWORZNO" },
      { name: "OSTROW WLKP" },
      { name: "PAJACZNO" },
      { name: "GDYNIA" },
      { name: "KWIDZYN" },
      { name: "MIADZYRZECZE GORNE" },
      { name: "KATOWICE" },
      { name: "KARKOW" },
      { name: "OLSZTYN" },
      { name: "LACHOWICE" },
      { name: "RYTWIANY" },
      { name: "SNIADOWO" },
      { name: "SIEPRAW 277" },
      { name: "ZLOTOW" },
      { name: "LNIANO" },
      { name: "BUK" },
      { name: "CHLUDOWO" },
      { name: "LOMűA" },
      { name: "PRUSZCZ GDAÁSKI" },
      { name: "MALCZKOWO" },
      { name: "MYSLENICE" },
      { name: "INOWROCLAW" },
      { name: "KOLONIA SWIDNIK MALY 53 D" },
      { name: "OSTROW WLKP." },
      { name: "ZABRZE" },
      { name: "ZARABY KOSCIELNE" },
      { name: "BADZIN" },
      { name: "JUSZCZYN" },
      { name: "SKAWINA" },
      { name: "BUDZISTOWO" },
      { name: "LISIA GORA" },
      { name: "NIEKANIN" },
      { name: "ZDUNY" },
      { name: "BIELSK PODLASKI" },
      { name: "ZGIERZ" },
      { name: "OSTROLAKA" },
      { name: "PRZYKONA" },
      { name: "LAGIEWNIKI NOWE" },
      { name: "CZARNKOW" },
      { name: "RYDULTOWY" },
      { name: "FABIANKI" },
      { name: "KLUCZBORK" },
      { name: "WOLCZYN" },
      { name: "LAZY" },
      { name: "GOSTYNIN" },
      { name: "OLSZYNA" },
      { name: "KONOPISKA" },
      { name: "KAMIONKA" },
      { name: "BOGUCHWALA" },
      { name: "STAWISKI" },
      { name: "NAMYSLOW" },
      { name: "RUDA SLASKA" },
      { name: "DABE WIELKIE" },
      { name: "TCZEW" },
      { name: "PULAWY" },
      { name: "BALICE" },
      { name: "KAPNO" },
      { name: "TOSZEK" },
      { name: "PI„TNICA" },
      { name: "KOLOBRZEG" },
      { name: "OSIEK NAD WISL„" },
      { name: "SUSZ" },
      { name: "BOLESLAWIEC" },
      { name: "GRODZISK WIELKOPOLSKI" },
      { name: "MYKANOW" },
      { name: "OLESNO" },
      { name: "SZUBIN" },
      { name: "STEGNA" },
      { name: "LUBNO GMIN WISKITKI" },
      { name: "STASZOW" },
      { name: "OLESNICA" },
      { name: "ELBL„G" },
      { name: "PLOCK" },
      { name: "WODZISLAW SLASKI" },
      { name: "SWIECIE" },
      { name: "PIECKI" },
      { name: "NOWOGARD" },
      { name: "MSZCZONOW" },
      { name: "PASLAK" },
      { name: "SIEDLCE" },
      { name: "HALINOW" },
      { name: "MLAWA" },
      { name: "LUBRANIEC" },
      { name: "ZARZECZE NISKO" },
      { name: "CHELM" },
      { name: "ZIELONA GORA" },
      { name: "RASZKOW" },
      { name: "SUWALKI" },
      { name: "OPATRZ MALA" },
      { name: "MIELEC" },
      { name: "ZAGNAÁSK" },
      { name: "WYSOKIE MAZOWIECKIE" },
      { name: "SEROCK" },
      { name: "LESZNO" },
      { name: "SLUPSK" },
      { name: "SWI„TNIKI GORNE" },
      { name: "CHRZANOW- BALIN" },
      { name: "JOZEFOW" },
      { name: "PRZYBYSZEWO" },
      { name: "JAZOWSKO" },
      { name: "WOLA BATORSKA" },
      { name: "SLAWNO" },
      { name: "POLICE" },
      { name: "TUREK" },
      { name: "CHOJNICE" },
      { name: "SLUPNO" },
      { name: "SWIEBODZIN" },
      { name: "MIROW" },
      { name: "GOLUB DOBRZYÁ" },
      { name: "SANOK" },
      { name: "ŹLINICE" },
      { name: "BARLINEK" },
      { name: "GOSTYÁ" },
      { name: "JAWORZE" },
      { name: "SWINNA" },
      { name: "SIERAKOW" },
      { name: "KOSZYCE WIELKIE" },
      { name: "SOCHOCIN" },
      { name: "MIADZYRZECZ" },
      { name: "KROSNO" },
      { name: "WITNICA" },
      { name: "CZOSNOW" },
      { name: "BRWINOW" },
      { name: "RUMIA" },
      { name: "RYMANOW" },
      { name: "NOWY S„CZ" },
      { name: "MSZANA DOLNA" },
      { name: "REGIMIN" },
      { name: "JODLOWNIK" },
      { name: "ADAMOWKA" },
      { name: "ZDUÁSKA WOLA" },
      { name: "GORZOW WLKP." },
      { name: "WALBRZYCH" },
      { name: "LUZINO" },
      { name: "RAWICZ" },
      { name: "GRUDZIADZ" },
      { name: "WOLOW" },
      { name: "BRODNICA" },
      { name: "POR„BKA IWKOWSKA" },
      { name: "PIASECZNO ZALESIE DOLNE" },
      { name: "RADOMSKO" },
      { name: "OSTROWICE" },
      { name: "HERBY" },
      { name: "D„BROWA TARNOWSKA" },
      { name: "RYBNO" },
      { name: "BRZOZOW" },
      { name: "SOCHACZEW" },
      { name: "WIEPRZ" },
      { name: "PIOTRKOW TRYB." },
      { name: "OLAWA" },
      { name: "BIALA PODLASKA" },
      { name: "SROCK" },
      { name: "SWIATNIKI GORNE" },
      { name: "LAPANOW" },
      { name: "DRAGACZ" },
      { name: "LIPNO" },
      { name: "NOWY TARG" },
      { name: "D„BROWKA" },
      { name: "KADZIERZYN KOŹLE" },
      { name: "WOLA RABKOWSKA" },
      { name: "MUSZYNA" },
      { name: "KOSINO" },
      { name: "RYCZYWOL" },
      { name: "WARKA" },
      { name: "KLUCZE-KRZYWOPLOTY" },
      { name: "BOBOWO" },
      { name: "LACZYCA K / POZNANIA" },
      { name: "OSIEK" },
      { name: "LEGNICA" },
      { name: "LUZINO," },
      { name: "WISLA" },
      { name: "MILANOWEK" },
      { name: "ZWONOWICE K/RYBNIKA" },
      { name: "ROKIETNICA" },
      { name: "KLODAWA" },
      { name: "KOSCIAN" },
      { name: "TRZCIANKA" },
      { name: "DAMNICA" },
      { name: "SLUPCA" },
      { name: "WEJHEROWO" },
      { name: "SERBIA & MONTENEGRO/ BELGRADE" },
      { name: "KRETOMINO" },
      { name: "D„BROWA GORNICZA" },
      { name: "SYRYNIA" },
      { name: "CHELMIEC" },
      { name: "BISKUPIEC" },
      { name: "POTWOROW" },
      { name: "DRWINIA" },
      { name: "KANIE K. PRUSZKOWA" },
      { name: "DROGOSZEWO" },
      { name: "GRODEK" },
      { name: "GOSCICINO" },
      { name: "ORZESZE-GARDOWICE" },
      { name: "MROZY" },
      { name: "WRZESNIA" },
      { name: "SIERAKOWICE" },
      { name: "ZGORZELEC-LAGOW" },
      { name: "AUGUSTOW" },
      { name: "WARSZAWA-WESOLA" },
      { name: "JANOW LUBELSKI" },
      { name: "BESTWINKA" },
      { name: "CZLUCHOW" },
      { name: "NOWA SOL" },
      { name: "WLOCHY" },
      { name: "LEGIONOWO" },
      { name: "WAGROW" },
      { name: "DABNO" },
      { name: "GOLUB - DOBRZYÁ" },
      { name: "OSTROWIEC SWIATOKRZYSKI" },
      { name: "űNIN" },
      { name: "POZNAN" },
      { name: "NOWY TOMYSL" },
      { name: "ZBYTKOW" },
      { name: "űUROMIN" },
      { name: "BORKOWO" },
      { name: "CHOJNOW" },
      { name: "DZIERűONIOW" },
      { name: "STRYKOW" },
      { name: "NIDZICA" },
      { name: "OűAROW MAZ./KAPUTY" },
      { name: "DOBRZEÁ MALY" },
      { name: "SIEMIANOWICE SLASKIE" },
      { name: "POGODKI" },
      { name: "BOCHNIA" },
      { name: "LOMIANKI" },
      { name: "KROTOSZYN " },
      { name: "NIECHORZE" },
      { name: "SWAROűYN" },
      { name: "MICHALOVCE" },
      { name: "GRONOWO GORNE" },
      { name: "MAJDAN KROLEWSKI" },
      { name: "JEűOW" },
      { name: "ILAWA" },
      { name: "MIASTKO" },
      { name: "ZBUCZYN" },
      { name: "BOJANOWO" },
      { name: "OűAROW" },
      { name: "PIOTRKOW TRYBUNALSKI" },
      { name: "KOSCIERZYNA" },
      { name: "SIERONIOWICE" },
      { name: "STRZELCE OPOLSKIE" },
      { name: "STASZEW" },
      { name: "KATRZYN" },
      { name: "BYTOW," },
      { name: "JEűOWA" },
      { name: "GASZOWICE" },
      { name: "KOTORZ MALY" },
      { name: "RECZ" },
      { name: "ZABLUDOW" },
      { name: "KARTUZY" },
      { name: "STRYSZAWA K. SUCHEJ BESKIDZKIE" },
      { name: "KROTOSZYNY" },
      { name: "MAJDAN NOWY" },
      { name: "BRZESKO" },
      { name: "NOWY DWOR MAZOWIECKI" },
      { name: "OSTRZESZOW" },
      { name: "WLOSZCZOWA" },
      { name: "KLOBUCK" },
      { name: "KOLECZKOWO" },
      { name: "RACIBORZ" },
      { name: "GNIEZNO" },
      { name: "GRYFINO-CZEPINO" },
      { name: "W„CHOCK" },
      { name: "KORNIK" },
      { name: "TARNOBRZEG" },
      { name: "KOKOSZKOWY" },
      { name: "ŹRODLA" },
      { name: "LEűAJSK" },
      { name: "MIECHOW" },
      { name: "ROűAN" },
      { name: "SKIERNIEWICE" },
      { name: "BULGARIA" },
      { name: "SIENIAWA" },
      { name: "OSTROW LUBELSKI" },
      { name: "STARA BIALA" },
      { name: "PYSKOWICE" },
      { name: "CYBINKA" },
      { name: "KCYNIA" },
      { name: "GRODKOW" },
      { name: "RANIűOW" },
      { name: "OSTROW MAZOWIECKA" },
      { name: "WIACBORK" },
      { name: "WLOSZAKOWICE" },
      { name: "PROSZOWICE" },
      { name: "ALWERNIA" },
      { name: "LUBIN" },
      { name: "K„PINO" },
      { name: "REDA" },
      { name: "CHELMEK" },
      { name: "MAJDAN" },
      { name: "OSJAKOW" },
      { name: "SIEPRAW" },
      { name: "BOBROWNIKI" },
      { name: "KRASNIK" },
      { name: "BEZLEDY" },
      { name: "STEPNICA" },
      { name: "SZCZERCOW" },
      { name: "SOSNO" },
      { name: "ROGOŹNO" },
      { name: "OSTROW WIELKOPOLSKI" },
      { name: "ZIABIENIEC" },
      { name: "SILNO" },
      { name: "LUDOMY" },
      { name: "DZIALDOWO" },
      { name: "POMIECZYNO" },
      { name: "KISZEWO" },
      { name: "BROJCE" },
      { name: "LUBARTOW" },
      { name: "BELGIUM " },
      { name: "D„BROWKA LUBIAÁSKA" },
      { name: "DOBRA" },
      { name: "BRUDZEW" },
      { name: "GLOGOWEK" },
      { name: "KRAKOW / LUCZANOWICE" },
      { name: "MIADZYBOROW" },
      { name: "MALOSZYNA" },
      { name: "SKARSZEWY" },
      { name: "KALISZ" },
      { name: "SZAMOTULY" },
      { name: "BIALOGARD" },
      { name: "STUDZIENICE" },
      { name: "NOWY MAJDAN" },
      { name: "GOLENIOW" },
      { name: "BYTOW" },
      { name: "W„BRZEŹNO" },
      { name: "GRYFICE" },
      { name: "RZESZOTARY" },
      { name: "űORY" },
      { name: "WIELICZKA" },
      { name: "TR„BKI WIELKIE" },
      { name: "TARNOW OPOLSKI" },
      { name: "MARCINKOWICE" },
      { name: "JAROSLAW" },
      { name: "KOMOROW" },
      { name: "KAMIENICA KROLEWSKA" },
      { name: "BRALIN" },
      { name: "GLIWICE" },
      { name: "MSTOW" },
      { name: "ZLOTOKLOS/RUNOW" },
      { name: "KONOPKI" },
      { name: "BRZOZA" },
      { name: "GRODZISK MAZOWIECKI" },
      { name: "NAKLO SLASKIE" },
      { name: "KOŹMIN WLKP." },
      { name: "RYDZYNA" },
      { name: "W„PIELSK" },
      { name: "GRYBOW" },
      { name: "SWIERZNO" },
      { name: "KARCZMISKA" },
      { name: "WI„ZOWNICA" },
      { name: "SULEJOWEK" },
      { name: "DRUűKOW PUSTY" },
      { name: "SZCZECINEK" },
      { name: "KAMIENNA GORA" },
      { name: "GLINIANKA" },
      { name: "DLUGOLAKA" },
      { name: "LUBLINIEC" },
      { name: "SIERPC" },
      { name: "WAGRY" },
      { name: "WLODAWA" },
      { name: "GLOGOW MALOPOLSKI" },
      { name: "OSINA " },
      { name: "WIESZOWA KGORNIKOW" },
      { name: "L„DEK ZDROJ" },
      { name: "LUTOMIERSK" },
      { name: "CIECHANOW" },
      { name: "SMIGIEL" },
      { name: "MYSLOWICE" },
      { name: "CZARNOGLOWY" },
      { name: "JANKI" },
      { name: "KATY" },
      { name: "DALESZYCE" },
      { name: "MIRKOW" },
      { name: "WASILKOW" },
      { name: "MOGILANY" },
      { name: "SPYTKOWICE" },
      { name: "SWARZADZ" },
      { name: "SLIWICE" },
      { name: "ILűA" },
      { name: "NOWY DWOR WEJHEROWSKI" },
      { name: "TLUSZCZ" },
      { name: "CIASNA" },
      { name: "BAJDY (K. KROSNA)" },
      { name: "PRUDA" },
      { name: "NOWA SLUPIA" },
      { name: "LUKOW" },
      { name: "LAZISKA GORNE" },
      { name: "KAZIMIERZA WIELKA" },
      { name: "UJSCIE" },
      { name: "PLAZA" },
      { name: "DOBRZYCA" },
      { name: "BILGORAJ" },
      { name: "PRUSZKOW" },
      { name: "SRODA WIELKOPOLSKA" },
      { name: "KOSOW LACKI" },
      { name: "BARCZEWKO" },
      { name: "WIERUSZOW" },
      { name: "PRZEŹMIEROWO" },
      { name: "RYN" },
      { name: "BARCIN" },
      { name: "NOWY BARKOCZYN 15" },
      { name: "OPACZ KOLONIA" },
      { name: "WISNIOWA" },
      { name: "RYKIĘ" },
      { name: "STARACHOWICE" },
      { name: "OLECKO" },
      { name: "JANOW" },
      { name: "BODZENTYN" },
      { name: "SKRZYDLNA" },
      { name: "ZAWADZKIE" },
      { name: "SLUBICE" },
      { name: "SWIDWIN" },
      { name: "STAWIGUDA K/OLSZTYNA" },
      { name: "RACI„ű" },
      { name: "ILOWA" },
      { name: "SMIEGIEL" },
      { name: "KONOPNICA" },
      { name: "STOPNICA" },
      { name: "TULOWICE" },
      { name: "JELCZ LASKOWICE" },
      { name: "LAÁCUT" },
      { name: "UZDOWO" },
      { name: "űERKOW" },
      { name: "BIALOBRZEGI RADOMSKIE" },
      { name: "KOBYLNICA" },
      { name: "CZARNA" },
      { name: "TUCHOLA" },
      { name: "CZECHOWICE-DZIEDZICE" },
      { name: "TAGOBORZE 325" },
      { name: "JASTKOWICE" },
      { name: "DZIERZKOWICE" },
      { name: "OSIEK N/WISL„" },
      { name: "LIDZBARK" },
      { name: "NAKLO" },
      { name: "STARE MIASTO K/KONINA" },
      { name: "RUDA HUTA" },
      { name: "PILCHOWICE" },
      { name: "JEűOWE" },
      { name: "WILKOWIECKO" },
      { name: "WISNIEWO" },
      { name: "PRZYTYK" },
      { name: "LISOW" },
      { name: "TYLMANOWA" },
      { name: "WOJCIECHOW" },
      { name: "WSOLA KOLO RADOMIA" },
      { name: "PERZOW" },
      { name: "SUCHEDNIOW" },
      { name: "WIACBORK - WITUNIA" },
      { name: "SOLEC KUJAWSKI" },
      { name: "STALOWA WOLA" },
      { name: "WOLSZTYN" },
      { name: "WILKOWISKO" },
      { name: "CHRZYPSKO WIELKIE" },
      { name: "SUSZEC" },
      { name: "PYSZNICA" },
      { name: "LADZICE" },
      { name: "MIERZYN/SZCZECIN" },
      { name: "WILKANOWO" },
      { name: "STRZEGOM" },
      { name: "MYSLIBORZ" },
      { name: "SWIDNIK" },
      { name: "GORLICE" },
      { name: "ILOWO - OSADA" },
      { name: "SWIERKLANY" },
      { name: "IWANOWICE" },
      { name: "RADZINY" },
      { name: "OPATOW" },
      { name: "KIELPINO" },
      { name: "DYGOWO" },
      { name: "LASK" },
      { name: "SZEMUD" },
      { name: "ZABKI" },
      { name: "KRASNYSTAW" },
      { name: "GRUDZADZ" },
      { name: "KARLINO" },
      { name: "PILA" },
      { name: "ROJEWO" },
      { name: "JUTROSIN" },
      { name: "ROZDRAűEW" },
      { name: "POLKOWICE" },
      { name: "MAKOW MAZOWIECKI" },
      { name: "CHWASZCZYNO K/GDYNI" },
      { name: "IÁSKO" },
      { name: "JADRZEJOW" },
      { name: "ZAWOJA" },
      { name: "CHELMűA" },
      { name: "LELIS" },
      { name: "SOKOLOW PODLASKI" },
      { name: "MEZOWO K. KARTUZ" },
      { name: "SKRZESZEW" },
      { name: "WADOWICE" },
      { name: "WIELISZEW" },
      { name: "GOCZALKOWICE" },
      { name: "GODZISZEWO" },
      { name: "GARWOLIN" },
      { name: "NOWA RUDA" },
      { name: "CHOJNE" },
      { name: "GRYFOW SL." },
      { name: "RZGOW" },
      { name: "GLOSKOW" },
      { name: "DZWIERZUTY MIATKIE" },
      { name: "WOLBORZ" },
      { name: "PAPOWO" },
      { name: "TOMASZOW MAZOWIECKI" },
      { name: "NOWY DWOR GDAÁSKI" },
      { name: "STRZEBIELINO" },
      { name: "PIASKI" },
      { name: "TERESIN" },
      { name: "GOLESZOW" },
      { name: "ROSTARZEWO" },
      { name: "SOKOLOW K/WARSZAWY" },
      { name: "WILCZYN" },
      { name: "STRAWCZYN" },
      { name: "LIMANOWA" },
      { name: "SLOÁSK" },
      { name: "LAG TARNOWSKI" },
      { name: "LINIEWO" },
      { name: "D„BROWA ZIELONA" },
      { name: "SOSONOWIEC" },
      { name: "KROTOSZYCE" },
      { name: "CHOCEÁ" },
      { name: "TURZE K/TCZEWA" },
      { name: "PLESNA" },
      { name: "MASLOW" },
      { name: "GDAÁSK- KOKOSZKI" },
      { name: "GORZYCE" },
      { name: "STRZELIN" },
      { name: "KURZATNIK" },
      { name: "RYBARZOWICE" },
      { name: "KOPALNIA" },
      { name: "RABA WYűNA" },
      { name: "BELűEC" },
      { name: "ZALUSKI" },
      { name: "KOLNO" },
      { name: "SUBKOWY" },
      { name: "PRZYJAŹÁ" },
      { name: "CZERNICA" },
      { name: "KOWALEW" },
      { name: "TRZEBINIA" },
      { name: "WESOLA" },
      { name: "TOMASZOW LUBELSKI" },
      { name: "CHODZIEű" },
      { name: "KSI„űENICE" },
      { name: "KATARZYNA" },
      { name: "ST„PORKOW" },
      { name: "NIEMODLIN (BRZEG)" },
      { name: "SZCZANIEC" },
      { name: "LUBISZEWO" },
      { name: "MIEDZIANA GORA" },
      { name: "BADKOW" },
      { name: "KABLOWO/ WEJHEROWA" },
      { name: "CZERNICA, WROCLAW" },
      { name: "KLUCZE" },
      { name: "GORZNO" },
      { name: "JELENIA GORA" },
      { name: "MORDY" },
      { name: "OJRZEÁ" },
      { name: "GOSWINOWICE" },
      { name: "JEDLINA ZDROJ" },
      { name: "PACZKOWO" },
      { name: "PRZASNYSZ" },
      { name: "GARBOW" },
      { name: "BRYNICA" },
      { name: "MYSZKOW" },
      { name: "SIDRA" },
      { name: "NOWA WIES WIELKA" },
      { name: "LOBEZ" },
      { name: "TENCZYNEK" },
      { name: "BIALA NIűN" },
      { name: "GRUSZCZYN" },
      { name: "SIEDLEC" },
      { name: "JASTKOW" },
      { name: "RADZIONKOW" },
      { name: "SIEMIATYCZE" },
      { name: "PODLAűE GM. NIEPOLOMICE" },
      { name: "KLOMNICE" },
      { name: "GORA KALWARIA" },
      { name: "STRONIE SLASKIE" },
      { name: "JABLONNA" },
      { name: "OZORKOW" },
      { name: "KRZESZOWICE" },
      { name: "PRZEMYSL" },
      { name: "PODEGRODZIE" },
      { name: "BOLACIN" },
      { name: "STAROGARD GDAÁSKI" },
      { name: "BZINICA NOWA" },
      { name: "LUKOWIEC" },
      { name: "KALISKA" },
      { name: "GOLDAP" },
      { name: "TOLKMICKO" },
      { name: "OSSOW" },
      { name: "JASTRZEBIA GORA" },
      { name: "IWANISKA" },
      { name: "GNOJNIK" },
      { name: "BELCHATOW " },
      { name: "USTRZYKI DOLNE" },
      { name: "ZAKILKOW" },
      { name: "KLAJ" },
      { name: "STRZALKOWO" },
      { name: "MORAWICA-BRZEZINY" },
      { name: "űARY" },
      { name: "SZCZYTNO" },
      { name: "PIÁCZOW" },
      { name: "PILZNO" },
      { name: "SKARBIMIERZ - OSIEDLE" },
      { name: "WEGROW" },
      { name: "LOPUSZNO" },
      { name: "GRYFINO" },
      { name: "UNISLAW" },
      { name: "BUSKO ZDROJ" },
      { name: "KOÁSKIE" },
      { name: "CHOSZCZNO" },
      { name: "MLYNARY" },
      { name: "SZPROTAWA" },
      { name: "CZERNICA-RATOWICE" },
      { name: "SLUPNO/CEKANOWO" },
      { name: "BOLSZEWO" },
      { name: "KLECZA GORNA" },
      { name: "SZTUM" },
      { name: "SZTUM-GORKI" },
      { name: "WILCZA GORA" },
      { name: "SYCOW" },
      { name: "GLOGOW" },
      { name: "BLASZKI" },
      { name: "KRASNOBROD" },
      { name: "WISLINA" },
      { name: "KLECZEW" },
      { name: "PNIEWO" },
      { name: "JADOWNIKI" },
      { name: "JASLO" },
      { name: "GORZOW WIELKOPOLSKI" },
      { name: "SIERADZ" },
      { name: "SZALEJOW GORNY" },
      { name: "SWIACIECHOWA" },
      { name: "KOWALEWO POMORSKIE" },
      { name: "KNUROW" },
      { name: "űAROW" },
      { name: "NOWA DABA" },
      { name: "MIÁSK MAZOWIECKI -STOJADLA" },
      { name: "PRZYSIECZ" },
      { name: "SPYTKOWICE-BACHOWICE" },
      { name: "RYKI" },
      { name: "ROŹWIENICA" },
      { name: "PUCK" },
      { name: "GLIWICE-BRZEZINKA" },
      { name: "GUTKOWO" },
      { name: "PELPLIN" },
      { name: "GOZD KOLO RADOMIA" },
      { name: "GOROWO-ILAWIECKIE" },
      { name: "KIELCZOW K/WROCLAWIA" },
      { name: "GOGOLOWA" },
      { name: "POLCZYN ZDROJ" },
      { name: "RYPIN" },
      { name: "SEROCK ODDZIAL LOWIN 48" },
      { name: "TRUSKOLASY" },
      { name: "NOWE MIASTO N/WART„" },
      { name: "JAZGRZEW" },
      { name: "JUCHNOWIEC KOSCIELNY" },
      { name: "MALOGOSZCZ" },
      { name: "NIEDŹWIADA" },
      { name: "STANISLAWOW" },
      { name: "GOCLAW" },
      { name: "KLINISKA" },
      { name: "BACZYNA" },
      { name: "PRZECLAW" },
      { name: "CELESTYNOW" },
      { name: "OSTROWIEC SW" },
      { name: "KOLBUDY" },
      { name: "K„KOLEWNICA" },
      { name: "JASIENICA" },
      { name: "BIELANY WROCLAWSKI" },
      { name: "KARCZEW" },
      { name: "ZABIERZOW" },
      { name: "KATY WROCLAWSKIE" },
      { name: "RYNARZEWO" },
      { name: "SIESTRZEÁ" },
      { name: "LACZNA" },
      { name: "TYMOWA" },
      { name: "L†DENSCHEID (NIEMCY)" },
      { name: "OBORNIKI WIELKOPOLSKIE" },
      { name: "LOMAZY" },
      { name: "MIAKINIA" },
      { name: "PONIEC" },
      { name: "SZYMISZOW" },
      { name: "KLAUDYN" },
      { name: "LUBSZA" },
      { name: "LUBOÁ" },
      { name: "MOR„G" },
      { name: "GOLUCHOW" },
      { name: "SOKOLKA" },
      { name: "JEDWABNE" },
      { name: "D„BROWKA LUBIAÁSKA K/ OPOLA" },
      { name: "CHOCIANOW" },
      { name: "CIECIERZYN" },
      { name: "JAKTOROW" },
      { name: "POBIEDZISKA" },
      { name: "KONIAKOW" },
      { name: "CZAPLINEK" },
      { name: "ALEKSANDROW LODZKI" },
      { name: "BUKOWINA TATRZ." },
      { name: "GDAÁSK - OSOWA" },
      { name: "TROJANOW" },
      { name: "STRACHOWKA" },
      { name: "POGWIZDOW NOWY 662" },
      { name: "SKOCZOW" },
      { name: "UJSOLY" },
      { name: "BRZEG" },
      { name: "GOROWO ILAWIECKIE" },
      { name: "KOBYLA GORA" },
      { name: "TRZEPOWO NOWE K/PLOCKA" },
      { name: "RDZAWKA" },
      { name: "BYSTRA" },
      { name: "POLANICA ZDROJ" },
      { name: "LYSKI" },
      { name: "PONIATOWA" },
      { name: "KALETY-MIOTEK" },
      { name: "BIALE BLOTA" },
      { name: "W„WOLNICA" },
      { name: "CHLEWISKA" },
      { name: "TYCZYN" },
      { name: "BYSTRZYCA KLODZKA" },
      { name: "JELCZ-LASKOWICE" },
      { name: "OLKUSZ" },
      { name: "CHWASZCZYNO" },
      { name: "KAÁCZUGA" },
      { name: "űELECHOW" },
      { name: "KARGOWA" },
      { name: "WIELEÁ" },
      { name: "BODZANOW" },
      { name: "ZAKLIKOW" },
      { name: "SKORCZ" },
      { name: "KADZIDLO" },
      { name: "KOCK" },
      { name: "OűAROW MAZOWIECKI" },
      { name: "KOZY" },
      { name: "SZCZUCIN" },
      { name: "GLOGOWO" },
      { name: "PUSTKOW" },
      { name: "WLYNKOWKO" },
      { name: "SKARűYSKO-KAMIENNA" },
      { name: "SLESIN" },
      { name: "TRZEBIATOW" },
      { name: "GRONOWO ELBL„SKIE" },
      { name: "LIBI„ű" },
      { name: "TOKARNIA" },
      { name: "BRATKOWICE" },
      { name: "BYCHAWA" },
      { name: "SKARZYSKO KAMIENNA" },
      { name: "SIEMINOWICE SLASKIE" },
      { name: "ROGOW" },
      { name: "ZYWIEC" },
      { name: "PISZ" },
      { name: "BARTOSZYCE" },
      { name: "STRZEBIELINO MORSKIE" },
      { name: "PIONKI " },
      { name: "KRASNOSIELC" },
      { name: "NOWOGROD BOBRZAÁSKI" },
      { name: "GIűYCKO" },
      { name: "NOWA TARG" },
      { name: "MARKI" },
      { name: "NOWE MIASTO" },
      { name: "MROWLA" },
      { name: "CZUDEC" },
      { name: "KROBANOW" },
      { name: "OSTRODA" },
      { name: "CZARNY BOR" },
      { name: "PROSZKOW K. OPOLA" },
      { name: "GRABOWKA" },
      { name: "BUCZKOWICE" },
      { name: "RADZYÁ PODLASKI" },
      { name: "NOWE BABICE" },
      { name: "SWIETOCHLOWICE" },
      { name: "KSIAűPOL" },
      { name: "SWIATOCHLOWICE" },
      { name: "SLAWKOW" },
      { name: "RACIECHOWICE " },
      { name: "LAZY-TURZA" },
      { name: "BOGACICA" },
      { name: "LAPY" },
      { name: "TOMICE K/WADOWIC" },
      { name: "OTRABUSY" },
      { name: "RUDNO" },
      { name: "PRZEMAT" },
      { name: "PIWNICZNA ZDROJ" },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("cities", null, {});
  },
};
